
services:
  wordpress:
    build:
      context: ./wordpress   # Указываем путь к Dockerfile для WordPress
      dockerfile: Dockerfile
    container_name: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
      DOMAIN_NAME: ${DOMAIN_NAME}  # Добавляем переменную для домена
      WP_ADMIN_USER: ${WP_ADMIN_USER}  # Имя администратора
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}  # Пароль администратора
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}  # Email администратора
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - wordpress_network
    command: ["/usr/local/bin/install-wordpress.sh"]  # Запуск скрипта установки WordPres

  php-fpm:
    build:
      context: ./php-fpm  # Указываем путь к Dockerfile для PHP-FPM
      dockerfile: Dockerfile
    container_name: php-fpm
    restart: always
    volumes:
      - wordpress_data:/var/www/html
      - ./wordpress/install-wordpress.sh:/usr/local/bin/install-wordpress.shl
      #- php-fpm-socket:/var/run/php  # Общий том для сокета
      - ./php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf
    networks:
      - wordpress_network
    #environment:
     # - PHP_FPM_LISTEN=/var/run/php/php-fpm.sock  # Указываем путь к сокету

  nginx:
    build:
      context: ./nginx  # Указываем путь к Dockerfile для Nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - wordpress_data:/var/www/html
      #- php-fpm-socket:/var/run/php  # Общий том для сокета
    depends_on:
      - php-fpm
    networks:
      - wordpress_network
    ports:
      - "80:80"
      - "443:443"

  db:
    image: postgres:latest
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-superuser.sql:/docker-entrypoint-initdb.d/init-superuser.sql  # Добавляем скрипт инициализации
    networks:
      - wordpress_network

volumes:
  wordpress_data:
  db_data:
  #php-fpm-socket:  # Определение общего тома для сокета

networks:
  wordpress_network:
    driver: bridge  # Указываем драйвер сети



